require: rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  Exclude:
    - 'spec/**/*.rb'

Style/RedundantFreeze:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/EndOfLine:
  Enabled: false