# frozen_string_literal: true

require_relative 'banking'
require_relative 'banking/constants'
require_relative 'banking/storage'
require_relative 'banking/card'
require_relative 'banking/cash_flow'
require_relative 'banking/base_tax'
require_relative 'banking/usual_tax'
require_relative 'banking/virtual_tax'
require_relative 'banking/capitalist_tax'
require_relative 'banking/tax'
require_relative 'banking/account'
require_relative 'banking/console_cashflow'
require_relative 'banking/console_account'
require_relative 'banking/console'
